### ISSUE TITLE
[Archlinux] Official image support

### ISSUE THREAD

**Issue by nlamirault** [multimediabs/plumb_unit#14]
Official Archlinux images are on the [Docker Hub](https://hub.docker.com/u/archlinux/)
See [announcement](https://lists.archlinux.org/pipermail/arch-dev-public/2017-May/028863.html)

**Comment by n0vember** [comment]
Typical me... I just made a new github project and pushed an archlinux image built from scratch. I suppose I'll have to remove it now.

Thanks for the tip, we will use this instead of the unofficial one we were using until now.
